# Generated by Django 4.1.3 on 2023-05-16 21:45

import backend.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    backend.customs.CustomCharField(
                        help_text="Referential Name",
                        max_length=100,
                        unique=True,
                        verbose_name="About Block Name",
                    ),
                ),
                (
                    "title",
                    backend.customs.CustomCharField(
                        help_text="Company Name", max_length=200, verbose_name="Title"
                    ),
                ),
                ("image", backend.customs.CustomImageFieldField(upload_to="about")),
            ],
            options={
                "verbose_name": "About Header",
                "verbose_name_plural": "About Headers",
            },
        ),
        migrations.CreateModel(
            name="CompanyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    backend.customs.CustomCharField(
                        help_text="Referential Name",
                        max_length=100,
                        unique=True,
                        verbose_name="Company History Name",
                    ),
                ),
                (
                    "title",
                    backend.customs.CustomCharField(
                        help_text="Section Title",
                        max_length=200,
                        verbose_name="Section Title",
                    ),
                ),
                (
                    "body",
                    backend.customs.CustomTextField(
                        help_text="Company History Body",
                        max_length=10000,
                        null=True,
                        verbose_name="Body",
                    ),
                ),
            ],
            options={
                "verbose_name": "Company History",
                "verbose_name_plural": "Company Historys",
            },
        ),
        migrations.CreateModel(
            name="MissionStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    backend.customs.CustomCharField(
                        help_text="Referential Name",
                        max_length=100,
                        unique=True,
                        verbose_name="Mission Statement Name",
                    ),
                ),
                (
                    "title",
                    backend.customs.CustomCharField(
                        help_text="Section Title",
                        max_length=200,
                        verbose_name="Section Title",
                    ),
                ),
                (
                    "body",
                    backend.customs.CustomTextField(
                        help_text="Mission Statement Body",
                        max_length=10000,
                        null=True,
                        verbose_name="Body",
                    ),
                ),
            ],
            options={
                "verbose_name": "Mission Statement",
                "verbose_name_plural": "Mission Statements",
            },
        ),
        migrations.CreateModel(
            name="Value",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    backend.customs.CustomCharField(
                        help_text="Value Title", max_length=100, verbose_name="Title"
                    ),
                ),
                (
                    "icon",
                    backend.customs.CustomCharField(
                        help_text="Value Icon", max_length=40, verbose_name="Icon"
                    ),
                ),
            ],
            options={
                "verbose_name": "Values",
                "verbose_name_plural": "Values",
            },
        ),
    ]
