# Generated by Django 4.1.3 on 2023-05-29 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="AboutBlock",
            new_name="AboutHeader",
        ),
    ]
