# Generated by Django 4.1.3 on 2023-05-29 19:18

import backend.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("about", "0002_rename_aboutblock_aboutheader"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutheader",
            name="name",
            field=backend.customs.CustomCharField(
                help_text="Referential Name",
                max_length=100,
                unique=True,
                verbose_name="Referential Name",
            ),
        ),
    ]
