# Generated by Django 4.1.3 on 2023-05-29 19:53

import backend.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Benefits",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    backend.customs.CustomCharField(
                        help_text="Header Text", max_length=100, verbose_name="Header"
                    ),
                ),
                (
                    "description",
                    backend.customs.CustomTextField(
                        help_text="Content Text",
                        max_length=250,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    backend.customs.CustomCharField(
                        help_text="Select Icon", max_length=40, verbose_name="Icon"
                    ),
                ),
                (
                    "buttonText",
                    backend.customs.CustomCharField(
                        help_text="Button Text",
                        max_length=40,
                        verbose_name="Button Text",
                    ),
                ),
                (
                    "page_link",
                    backend.customs.CustomCharField(
                        default="about",
                        help_text="Page Link",
                        max_length=40,
                        verbose_name="Link",
                    ),
                ),
            ],
            options={
                "verbose_name": "Benefits",
                "verbose_name_plural": "Benefits",
            },
        ),
        migrations.CreateModel(
            name="Feature",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detail",
                    backend.customs.CustomCharField(
                        help_text="Feature Detail",
                        max_length=100,
                        verbose_name="Feature Detail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Feature",
                "verbose_name_plural": "Features",
            },
        ),
        migrations.CreateModel(
            name="ProcessTextItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    backend.customs.CustomCharField(
                        help_text="Header", max_length=100, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    backend.customs.CustomTextField(
                        help_text="Description",
                        max_length=500,
                        verbose_name="Description",
                    ),
                ),
                (
                    "icon",
                    backend.customs.CustomCharField(
                        help_text="Select Icon", max_length=40, verbose_name="Icon"
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Text Item",
                "verbose_name_plural": "Process Text Items",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SupportedSites",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "detail",
                    backend.customs.CustomCharField(
                        help_text="Supported Site Detail",
                        max_length=100,
                        verbose_name="Supported Site Detail",
                    ),
                ),
            ],
            options={
                "verbose_name": "Supported Sites",
                "verbose_name_plural": "Supported Sites",
            },
        ),
        migrations.CreateModel(
            name="ServiceTier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        help_text="Image",
                        upload_to="pricing_images",
                        verbose_name="Image",
                    ),
                ),
                (
                    "service_title",
                    backend.customs.CustomCharField(
                        db_index=True,
                        help_text="Service Tier Title",
                        max_length=100,
                        verbose_name="Service Title",
                    ),
                ),
                (
                    "price",
                    backend.customs.CustomDecimalField(
                        decimal_places=2,
                        help_text="Service Tier Price",
                        max_digits=10,
                        verbose_name="Price",
                    ),
                ),
                (
                    "paragraph_one",
                    backend.customs.CustomTextField(
                        help_text="Paragraph One",
                        max_length=500,
                        verbose_name="Paragraph One",
                    ),
                ),
                (
                    "paragraph_two",
                    backend.customs.CustomTextField(
                        help_text="Paragraph Two",
                        max_length=500,
                        verbose_name="Paragraph Two",
                    ),
                ),
                (
                    "paragraph_three",
                    backend.customs.CustomTextField(
                        help_text="Paragraph Three",
                        max_length=500,
                        verbose_name="Paragraph Three",
                    ),
                ),
                (
                    "features",
                    backend.customs.CustomManyToManyField(
                        help_text="Service Tier Features",
                        related_name="features",
                        to="services.feature",
                        verbose_name="Features",
                    ),
                ),
                (
                    "supported_sites",
                    backend.customs.CustomManyToManyField(
                        help_text="Service Tier Supported Sites",
                        related_name="supportedsites",
                        to="services.supportedsites",
                        verbose_name="Supported Sites",
                    ),
                ),
            ],
            options={
                "verbose_name": "Service Tiers",
                "verbose_name_plural": "Service Tiers",
                "ordering": ["price"],
            },
        ),
        migrations.CreateModel(
            name="ProcessImageItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="process_images", verbose_name="Image"),
                ),
                (
                    "servicetier",
                    models.ForeignKey(
                        help_text="Service Tier Link",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="servicetier",
                        to="services.servicetier",
                        verbose_name="Service Tier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Process Image Item",
                "verbose_name_plural": "Process Image Items",
            },
        ),
    ]
