# Generated by Django 4.1.3 on 2023-06-13 23:23

import backend.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_alter_servicetier_features_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContentTextBlock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    backend.customs.CustomCharField(
                        db_index=True,
                        help_text="Identifier",
                        max_length=20,
                        unique=True,
                        verbose_name="Slug",
                    ),
                ),
                (
                    "title",
                    backend.customs.CustomCharField(
                        help_text="Header", max_length=200, verbose_name="Title"
                    ),
                ),
                (
                    "description",
                    backend.customs.CustomTextField(
                        help_text="Description",
                        max_length=300,
                        verbose_name="Description",
                    ),
                ),
            ],
            options={
                "verbose_name": "Content Text Blocks",
                "verbose_name_plural": "Content Text Blocks",
            },
        ),
    ]
