# Generated by Django 4.1.3 on 2023-05-16 21:23

import backend.customs
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    backend.customs.CustomCharField(
                        db_index=True,
                        default="Placeholder",
                        help_text="Task Title",
                        max_length=100,
                        verbose_name="Task Title",
                    ),
                ),
                (
                    "description",
                    backend.customs.CustomTextField(
                        blank=True,
                        help_text="Description (Optional)",
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "status",
                    backend.customs.CustomCharField(
                        choices=[
                            ("Incomplete", "Incomplete"),
                            ("Complete", "Complete"),
                        ],
                        default="Incomplete",
                        help_text="Task Status",
                        max_length=20,
                        verbose_name="Task Status",
                    ),
                ),
                (
                    "priority",
                    backend.customs.CustomCharField(
                        choices=[
                            ("None", "None"),
                            ("Low", "Low"),
                            ("Medium", "Medium"),
                            ("High", "High"),
                        ],
                        default="None",
                        help_text="Task Priority",
                        max_length=10,
                        verbose_name="Task Priority",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    backend.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_query_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "Task",
                "verbose_name_plural": "Tasks",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TaskSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    backend.customs.CustomCharField(
                        db_index=True,
                        default="Placeholder",
                        help_text="Section Title",
                        max_length=100,
                        verbose_name="Section Title",
                    ),
                ),
                (
                    "description",
                    backend.customs.CustomTextField(
                        blank=True,
                        help_text="Description (Optional)",
                        max_length=300,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "order",
                    backend.customs.CustomPositiveIntegerField(
                        default=0, verbose_name="Order within List"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    backend.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_query_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "tasks",
                    models.ManyToManyField(
                        related_name="get_task_lists", to="tasks.task"
                    ),
                ),
            ],
            options={
                "verbose_name": "Task Section",
                "verbose_name_plural": "Task Sections",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="TaskList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    backend.customs.CustomCharField(
                        db_index=True,
                        default="Placeholder",
                        help_text="Task List Title",
                        max_length=100,
                        verbose_name="Task List Title",
                    ),
                ),
                (
                    "description",
                    backend.customs.CustomTextField(
                        blank=True,
                        help_text="Description (Optional)",
                        max_length=300,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, null=True)),
                (
                    "author",
                    backend.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_query_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "sections",
                    models.ManyToManyField(
                        related_name="task_sections", to="tasks.tasksection"
                    ),
                ),
            ],
            options={
                "verbose_name": "Task List",
                "verbose_name_plural": "Task Lists",
                "ordering": ["id"],
            },
        ),
    ]
