# Generated by Django 4.1.3 on 2023-05-29 19:52

import backend.customs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("landing", "0002_rename_heroblock_heroheader_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="servicetier",
            name="features",
        ),
        migrations.RemoveField(
            model_name="servicetier",
            name="supported_sites",
        ),
        migrations.AlterField(
            model_name="sectionheader",
            name="description",
            field=backend.customs.CustomTextField(
                blank=True,
                help_text="Description Text",
                max_length=250,
                null=True,
                verbose_name="Description",
            ),
        ),
        migrations.DeleteModel(
            name="Feature",
        ),
        migrations.DeleteModel(
            name="ServiceTier",
        ),
        migrations.DeleteModel(
            name="SupportedSites",
        ),
    ]
