import { Breakpoints } from '../common';

export interface Colors {
  transparent: string;
  almostBlack: string;
  lightBlack: string;
  almostWhite: string;
  veryDarkBlue: string;
  slate: string;
  slateLight: string;
  slateDark: string;
  smoke: string;
  smokeLight: string;
  smokeDark: string;
  white: string;
  white05: string;
  white10: string;
  white50: string;
  white75: string;
  black: string;
  black05: string;
  black10: string;
  black50: string;
  black75: string;
  accent: string;
  yellow: string;
  warmGrey: string;
  searchHighlight: string;
  danger: string;
  warning: string;
  success: string;
  info: string;
  brand: {
    red: string;
    pink: string;
    purple: string;
    blue: string;
    marine: string;
    green: string;
    yellow: string;
  };
}

export interface BaseTheme extends Colors {
  breakpoints: Breakpoints;
  shadows: Record<number, string>;
  sp: (...values: number[]) => string;
  backgroundTransition: string;
  fontFamily: string;
  fontFamilyMono: string;
  fontWeight: number;
  textHighlight: string;
  textHighlightForeground: string;
  accentText: string;
  selected: string;
  noticeInfoBackground: string;
  noticeInfoText: string;
  noticeTipBackground: string;
  noticeTipText: string;
  noticeWarningBackground: string;
  noticeWarningText: string;
  noticeSuccessBackground: string;
  noticeSuccessText: string;
  tableSelectedBackground: string;
}

export interface ExtendedTheme extends BaseTheme {
  isDark: true | false;
  buttonNeutralBackground: string;
  buttonNeutralText: string;
  buttonNeutralBorder: string;
  divider: string;
  background: string;
  secondaryBackground: string;
  link: string;
  cursor: string;
  backdrop: string;
  commentBackground: string;
  mentionBackground: string;
  progressBarBackground: string;
  scrollbarBackground: string;
  scrollbarThumb: string;
  inputBorder: string;
  inputBorderFocused: string;
  listItemHoverBackground: string;
  menuItemSelected: string;
  menuBackground: string;
  menuShadow: string;
  modalBackdrop: string;
  modalBackground: string;
  modalShadow: string;
  noticeInfoText: string;
  noticeTipText: string;
  noticeWarningText: string;
  noticeSuccessText: string;
  sidebarBackground: string;
  sidebarActiveBackground: string;
  sidebarControlHoverBackground: string;
  sidebarDraftBorder: string;
  sidebarText: string;
  tableDivider: string;
  tableSelected: string;
  text: string;
  textSecondary: string;
  textTertiary: string;
  textDiffInserted: string;
  textDiffInsertedBackground: string;
  textDiffDeleted: string;
  textDiffDeletedBackground: string;
  toolbarHoverBackground: string;
  toolbarBackground: string;
  toolbarInput: string;
  toolbarItem: string;
  tooltipBackground: string;
  tooltipText: string;
}
