# Generated by Django 4.1.3 on 2023-05-22 20:32

import backend.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Requirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="Responsibilities",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("detail", models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name="JobPosting",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "position",
                    backend.customs.CustomCharField(
                        db_index=True,
                        help_text="Job Title/Position",
                        max_length=40,
                        verbose_name="Position",
                    ),
                ),
                (
                    "location",
                    backend.customs.CustomCharField(
                        help_text="Job Location", max_length=80, verbose_name="Location"
                    ),
                ),
                (
                    "type",
                    backend.customs.CustomCharField(
                        help_text="Employment Type", max_length=20, verbose_name="Type"
                    ),
                ),
                (
                    "tagline",
                    backend.customs.CustomTextField(
                        help_text="Job Post Tagline",
                        max_length=100,
                        null=True,
                        verbose_name="Tagline",
                    ),
                ),
                (
                    "who_we_are",
                    backend.customs.CustomTextField(
                        help_text="Who We Are Text",
                        max_length=500,
                        verbose_name="Who We Are",
                    ),
                ),
                (
                    "looking_for",
                    backend.customs.CustomTextField(
                        help_text="Looking For Text",
                        max_length=500,
                        null=True,
                        verbose_name="Looking For",
                    ),
                ),
                (
                    "why_apply",
                    backend.customs.CustomTextField(
                        help_text="Why Apply Text",
                        max_length=500,
                        verbose_name="Why Apply",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "filled",
                    models.BooleanField(
                        db_index=True,
                        default=False,
                        help_text="Filled Status",
                        verbose_name="Filled",
                    ),
                ),
                (
                    "requirements",
                    models.ManyToManyField(
                        help_text="Job Requirements",
                        related_name="requirement",
                        to="jobs.requirement",
                        verbose_name="Requirements",
                    ),
                ),
                (
                    "responsibilities",
                    models.ManyToManyField(
                        help_text="Job Responsibilities",
                        related_name="responsibilities",
                        to="jobs.responsibilities",
                        verbose_name="Responsibilities",
                    ),
                ),
            ],
            options={
                "verbose_name": "Job Openings",
                "verbose_name_plural": "Job Openings",
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "first_name",
                    backend.customs.CustomCharField(
                        help_text="First Name", max_length=30, verbose_name="First Name"
                    ),
                ),
                (
                    "last_name",
                    backend.customs.CustomCharField(
                        help_text="Last Name", max_length=30, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    backend.customs.CustomEmailField(
                        help_text="Email Address", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    backend.customs.CustomCharField(
                        help_text="Phone Number", max_length=20, verbose_name="Phone"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "city",
                    backend.customs.CustomCharField(
                        help_text="City", max_length=40, verbose_name="City"
                    ),
                ),
                (
                    "zipcode",
                    backend.customs.CustomCharField(
                        help_text="Zip Code", max_length=15, verbose_name="Zip Code"
                    ),
                ),
                (
                    "resume",
                    models.FileField(
                        blank=True,
                        help_text="Supported file types: PDF, Microsoft Word, plain text.",
                        null=True,
                        upload_to="resumes/",
                        verbose_name="Resume",
                    ),
                ),
                (
                    "status",
                    backend.customs.CustomCharField(
                        choices=[
                            ("Pending", "Pending"),
                            ("Reviewing", "Reviewing"),
                            ("Rejected", "Rejected"),
                            ("Accepted", "Accepted"),
                        ],
                        db_index=True,
                        default="Pending",
                        help_text="Application Status",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "job",
                    models.ForeignKey(
                        default=1,
                        help_text="Related Job",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="job",
                        to="jobs.jobposting",
                        verbose_name="Job",
                    ),
                ),
            ],
            options={
                "verbose_name": "Application",
                "verbose_name_plural": "Applications",
                "ordering": ["-id"],
            },
        ),
    ]
