# Generated by Django 4.1.3 on 2023-05-16 22:25

import backend.customs
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    backend.customs.CustomCharField(
                        db_index=True,
                        default="Placeholder",
                        help_text="Table Name",
                        max_length=50,
                        verbose_name="Table Name",
                    ),
                ),
            ],
            options={
                "verbose_name": "Table",
                "verbose_name_plural": "Tables",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Row",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    backend.customs.CustomCharField(
                        blank=True,
                        db_index=True,
                        help_text="Row Name",
                        max_length=50,
                        null=True,
                        verbose_name="Row Name",
                    ),
                ),
                (
                    "table",
                    backend.customs.CustomForeignKeyField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rows",
                        to="tables.table",
                        verbose_name="Table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Row",
                "verbose_name_plural": "Rows",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Column",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    backend.customs.CustomCharField(
                        db_index=True,
                        help_text="Column Name",
                        max_length=50,
                        verbose_name="Column Name",
                    ),
                ),
                (
                    "table",
                    backend.customs.CustomForeignKeyField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="columns",
                        to="tables.table",
                        verbose_name="Table",
                    ),
                ),
            ],
            options={
                "verbose_name": "Column",
                "verbose_name_plural": "Columns",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Cell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "value",
                    backend.customs.CustomCharField(
                        db_index=True,
                        help_text="Cell Value",
                        max_length=255,
                        verbose_name="Cell Value",
                    ),
                ),
                (
                    "column",
                    backend.customs.CustomForeignKeyField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="tables.column",
                        verbose_name="Column",
                    ),
                ),
                (
                    "row",
                    backend.customs.CustomForeignKeyField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cells",
                        to="tables.row",
                        verbose_name="Row",
                    ),
                ),
            ],
            options={
                "verbose_name": "Cell",
                "verbose_name_plural": "Cells",
                "ordering": ["id"],
            },
        ),
    ]
