# Generated by Django 4.1.3 on 2023-07-09 22:48

import api.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="HeroHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        db_index=True,
                        help_text="Referential Name",
                        max_length=100,
                        unique=True,
                        verbose_name="Hero Block Name",
                    ),
                ),
                (
                    "title",
                    api.customs.CustomCharField(
                        help_text="Header", max_length=200, verbose_name="Title"
                    ),
                ),
                (
                    "subtitle",
                    api.customs.CustomTextField(
                        blank=True,
                        help_text="Subtitle",
                        max_length=500,
                        null=True,
                        verbose_name="Subtitle",
                    ),
                ),
                (
                    "description",
                    api.customs.CustomTextField(
                        blank=True,
                        help_text="Description",
                        max_length=500,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "buttonText",
                    api.customs.CustomCharField(
                        help_text="Button Text",
                        max_length=50,
                        verbose_name="Button Text",
                    ),
                ),
            ],
            options={
                "verbose_name": "Hero Header",
                "verbose_name_plural": "Hero Headers",
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SectionHeader",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    api.customs.CustomCharField(
                        db_index=True,
                        help_text="Referential Name",
                        max_length=100,
                        unique=True,
                        verbose_name="Section Name",
                    ),
                ),
                (
                    "subtitle",
                    api.customs.CustomCharField(
                        help_text="Subheader Text",
                        max_length=100,
                        verbose_name="Subheader",
                    ),
                ),
                (
                    "title",
                    api.customs.CustomCharField(
                        help_text="Header Text", max_length=100, verbose_name="Header"
                    ),
                ),
                (
                    "description",
                    api.customs.CustomTextField(
                        blank=True,
                        help_text="Description Text",
                        max_length=250,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "alignment",
                    api.customs.CustomCharField(
                        choices=[
                            ("Left", "Left"),
                            ("Right", "Right"),
                            ("Center", "Center"),
                        ],
                        help_text="Text Alignment",
                        max_length=10,
                        verbose_name="Text Alignment",
                    ),
                ),
                (
                    "show_divider",
                    models.BooleanField(
                        default=False,
                        help_text="Optional Divider Below Section Header",
                        verbose_name="Bottom Divider",
                    ),
                ),
            ],
            options={
                "verbose_name": "Section Header",
                "verbose_name_plural": "Section Headers",
                "ordering": ["name"],
            },
        ),
    ]
