# Generated by Django 4.1.3 on 2023-07-10 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0002_posttag_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="post", to="home.posttag", verbose_name="Tags"
            ),
        ),
    ]
