from django.urls import path
from .views import *

urlpatterns = [
    #
    #       General
    #
    path(
        "home/",
        HomeFullTestView.as_view(),
        name="home-full",
    ),
    #
    #       Hero Header
    #
    path(
        "heroheader/main/",
        HeroHeaderMainAPIView.as_view(),
        name="heroheader-main",
    ),
    path(
        "heroheader/",
        HeroHeaderView.as_view(),
        name="heroheader-list",
    ),
    path(
        "heroheader/<int:pk>/",
        HeroHeaderView.as_view(),
        name="heroheader-detail",
    ),
    path(
        "heroheader/bulk/",
        HeroHeaderBulkView.as_view(),
        name="heroheader-bulk-detail",
    ),
    #
    #       Section Header
    #
    path(
        "sectionheader/",
        SectionHeaderView.as_view(),
        name="sectionheader-list",
    ),
    path(
        "sectionheader/<int:pk>/",
        SectionHeaderView.as_view(),
        name="sectionheader-detail",
    ),
    path(
        "sectionheader/<str:name>/",
        SectionHeaderSearchView.as_view(),
        name="sectionheader-search",
    ),
    path(
        "sectionheader/del/bulk/",
        SectionHeaderBulkView.as_view(),
        name="sectionheader-bulk-detail",
    ),
    #
    #       Tags
    #
    path(
        "tags/",
        TagView.as_view(),
        name="posttag-list",
    ),
    path(
        "tags/<int:pk>/",
        TagView.as_view(),
        name="posttag-detail",
    ),
    path(
        "tags/del/bulk/",
        TagBulkView.as_view(),
        name="posttag-bulk-detail",
    ),
    #
    #       Posts
    #
    path(
        "post/",
        PostView.as_view(),
        name="post-list",
    ),
    path(
        "post/<int:pk>/",
        PostView.as_view(),
        name="post-detail",
    ),
    path(
        "posts/recent/",
        RecentPostView.as_view(),
        name="recent-posts",
    ),
    path(
        "posts/highlighted/",
        HighlightedPostView.as_view(),
        name="highlighted-posts",
    ),
]
