# Generated by Django 4.1.3 on 2023-05-16 21:16

import backend.customs
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Messages",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    backend.customs.CustomCharField(
                        help_text="Full Name", max_length=50, verbose_name="Name"
                    ),
                ),
                (
                    "email",
                    backend.customs.CustomEmailField(
                        help_text="Email Address", max_length=254, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    backend.customs.CustomCharField(
                        help_text="Phone Number", max_length=20, verbose_name="Phone"
                    ),
                ),
                (
                    "subject",
                    backend.customs.CustomCharField(
                        help_text="Message Subject",
                        max_length=100,
                        verbose_name="Subject",
                    ),
                ),
                (
                    "message",
                    backend.customs.CustomTextField(
                        help_text="Message Content",
                        max_length=20000,
                        verbose_name="Message",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Created At"),
                ),
                (
                    "is_read",
                    backend.customs.CustomBooleanField(
                        db_index=True,
                        default=False,
                        help_text="Is Read Status",
                        verbose_name="Is Read",
                    ),
                ),
                (
                    "is_archived",
                    backend.customs.CustomBooleanField(
                        db_index=True,
                        default=False,
                        help_text="Is Archived Status",
                        verbose_name="Is Archived",
                    ),
                ),
            ],
            options={
                "verbose_name": "Messages",
                "verbose_name_plural": "Messages",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Subscribers",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "email",
                    backend.customs.CustomEmailField(
                        db_index=True,
                        help_text="Email Address",
                        max_length=254,
                        unique=True,
                        verbose_name="Email",
                    ),
                ),
                (
                    "subscribed_on",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Subscribed On"
                    ),
                ),
            ],
            options={
                "verbose_name": "Subscribers",
                "verbose_name_plural": "Subscribers",
            },
        ),
    ]
