# Generated by Django 4.1.3 on 2023-05-16 22:25

import backend.customs
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="FAQAnswer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    backend.customs.CustomCharField(
                        db_index=True,
                        default="Placeholder",
                        help_text="Element Name",
                        max_length=50,
                        verbose_name="Element Name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "answer",
                    backend.customs.CustomTextField(
                        blank=True,
                        help_text="Answer",
                        max_length=500,
                        null=True,
                        verbose_name="Answer",
                    ),
                ),
                (
                    "author",
                    backend.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_query_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ Answer",
                "verbose_name_plural": "FAQ Answers",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="FAQQuestion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    backend.customs.CustomCharField(
                        db_index=True,
                        default="Placeholder",
                        help_text="Element Name",
                        max_length=50,
                        verbose_name="Element Name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "question",
                    backend.customs.CustomTextField(
                        blank=True,
                        help_text="Question",
                        max_length=500,
                        null=True,
                        verbose_name="Question",
                    ),
                ),
                (
                    "author",
                    backend.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_query_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ Question",
                "verbose_name_plural": "FAQ Questions",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="FAQQuestionCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    backend.customs.CustomCharField(
                        db_index=True,
                        default="Placeholder",
                        help_text="Element Name",
                        max_length=50,
                        verbose_name="Element Name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "author",
                    backend.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_query_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ Question Category",
                "verbose_name_plural": "FAQ Question Categorys",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="FAQSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    backend.customs.CustomCharField(
                        db_index=True,
                        default="Placeholder",
                        help_text="Element Name",
                        max_length=50,
                        verbose_name="Element Name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "type",
                    backend.customs.CustomCharField(
                        choices=[
                            ("Tabbed", "Tabbed"),
                            ("List", "List"),
                            ("Condensed", "Condensed"),
                        ],
                        default="Tabbed",
                        help_text="FAQ Type",
                        max_length=10,
                        verbose_name="FAQ Type",
                    ),
                ),
                (
                    "description",
                    backend.customs.CustomTextField(
                        blank=True,
                        help_text="Description (Optional)",
                        max_length=300,
                        null=True,
                        verbose_name="Description",
                    ),
                ),
                (
                    "author",
                    backend.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_query_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ Set",
                "verbose_name_plural": "FAQ Sets",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="FAQQuestionSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    backend.customs.CustomCharField(
                        db_index=True,
                        default="Placeholder",
                        help_text="Element Name",
                        max_length=50,
                        verbose_name="Element Name",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    backend.customs.CustomPositiveIntegerField(
                        default=0, verbose_name="Appearance Order within Category"
                    ),
                ),
                (
                    "author",
                    backend.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.SET_DEFAULT,
                        related_query_name="author",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Author",
                    ),
                ),
                (
                    "faq_answer",
                    backend.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="faq_answer",
                        to="faqs.faqanswer",
                        verbose_name="FAQ Answer",
                    ),
                ),
                (
                    "faq_category",
                    backend.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="faq_category",
                        to="faqs.faqquestioncategory",
                        verbose_name="FAQ Question Category",
                    ),
                ),
                (
                    "faq_question",
                    backend.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_query_name="faq_question",
                        to="faqs.faqquestion",
                        verbose_name="FAQ Question",
                    ),
                ),
                (
                    "faqset",
                    backend.customs.CustomForeignKeyField(
                        default=1,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="question_sets",
                        related_query_name="faqset",
                        to="faqs.faqset",
                        verbose_name="FAQSet",
                    ),
                ),
            ],
            options={
                "verbose_name": "FAQ Question Set",
                "verbose_name_plural": "FAQ Question Sets",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="faqanswer",
            name="faq_question",
            field=backend.customs.CustomForeignKeyField(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_query_name="faq_question",
                to="faqs.faqquestion",
                verbose_name="FAQ Question",
            ),
        ),
    ]
