from django.urls import path
from .views import *

urlpatterns = [
    path(
        "value/",
        ValueAPIView.as_view(),
        name="value-list",
    ),
    path(
        "value/<int:pk>/",
        ValueDetailAPIView.as_view(),
        name="value-detail",
    ),
    path(
        "value/bulk/",
        ValueBulkAPIView.as_view(),
        name="value-bulk-detail",
    ),
    path(
        "aboutheader/",
        AboutHeaderAPIView.as_view(),
        name="aboutheader-list",
    ),
    path(
        "aboutheader/<int:pk>/",
        AboutHeaderDetailAPIView.as_view(),
        name="aboutheader-detail",
    ),
    path(
        "aboutheader/bulk/",
        AboutHeaderBulkAPIView.as_view(),
        name="aboutheader-bulk-detail",
    ),
    path(
        "missionstatement/",
        MissionStatementAPIView.as_view(),
        name="missionstatement-list",
    ),
    path(
        "missionstatement/<int:pk>/",
        MissionStatementDetailAPIView.as_view(),
        name="missionstatement-update",
    ),
    path(
        "missionstatement/bulk/",
        MissionStatementBulkAPIView.as_view(),
        name="missionstatement-bulk-detail",
    ),
    path(
        "companyhistory/",
        CompanyHistoryAPIView.as_view(),
        name="companyhistory-list",
    ),
    path(
        "companyhistory/<int:pk>/",
        CompanyHistoryDetailAPIView.as_view(),
        name="companyhistory-update",
    ),
    path(
        "companyhistory/bulk/",
        CompanyHistoryBulkAPIView.as_view(),
        name="companyhistory-bulk-detail",
    ),
    path(
        "about/",
        AboutFullView.as_view(),
        name="about-full",
    ),
]
