from django.urls import path
from .views import *


urlpatterns = [
    path(
        "landing/",
        LandingFullTestView.as_view(),
        name="landing-full",
    ),
    path(
        "process/",
        ProcessAPIView.as_view(),
        name="process-list",
    ),
    path(
        "process/<int:pk>/",
        ProcessDetailAPIView.as_view(),
        name="process-detail",
    ),
    path(
        "process/bulk/",
        ProcessBulkAPIView.as_view(),
        name="process-bulk-detail",
    ),
    path(
        "heroheader/main/",
        HeroHeaderMainAPIView.as_view(),
        name="heroheader-single",
    ),
    path(
        "heroheader/",
        HeroHeaderAPIView.as_view(),
        name="heroheader-list",
    ),
    path(
        "heroheader/<int:pk>/",
        HeroHeaderDetailAPIView.as_view(),
        name="heroheader-detail",
    ),
    path(
        "heroheader/bulk/",
        HeroHeaderBulkAPIView.as_view(),
        name="heroheader-bulk-detail",
    ),
    path(
        "sectionheader/",
        SectionHeaderAPIView.as_view(),
        name="sectionheader-list",
    ),
    path(
        "sectionheader/<int:pk>/",
        SectionHeaderUpdateAPIView.as_view(),
        name="sectionheader-update",
    ),
    path(
        "sectionheader/<str:name>/",
        SectionHeaderDetailAPIView.as_view(),
        name="sectionheader-search",
    ),
    path(
        "sectionheader/del/bulk/",
        SectionHeaderBulkAPIView.as_view(),
        name="sectionheader-bulk-detail",
    ),
    path(
        "latestnews/",
        LatestPostsAPIView.as_view(),
        name="latestposts-list",
    ),
    path(
        "latestposts/<int:pk>/",
        LatestPostsDetailView.as_view(),
        name="latestposts-detail",
    ),
    path(
        "latestposts/bulk/",
        LatestPostsBulkAPIView.as_view(),
        name="latestposts-bulk-detail",
    ),
]
